services:
  redis:
    image: redis

  rspamd:
    build: ./rspamd/
    image: rspamd-img
    environment:
      - REDIS_ADDRESS=redis
  opensmtpd:
    build: ./opensmtpd/
    image: opensmtpd-img
    ports:
      - "465:465"
      - "587:587"
